### PR TITLE
Add JSON Schema validations

### PR DESCRIPTION
**Pull request by KendallWeihe**
Leverage Rust build script to automatically generate the JSON Schemas at https://github.com/TBD54566975/tbdex/blob/main/hosted/json-schemas into source code. This way it's all included in the single binary.

A few places with `// 🚧 TODO commenting out until did:dht support`

### CODE REVIEW

**Comment by nitro-neal** [comment]
so this is pretty cool.

I guess an alternative would be just to copy paste the schemas in a folder, and then have a static function lazy load them programmatically  ?

**Review by nitro-neal — APPROVED** [review]

**Comment by KendallWeihe** [comment]
> so this is pretty cool.
> 
> I guess an alternative would be just to copy paste the schemas in a folder, and then have a static function lazy load them programmatically ?

I think we have room for improvement, but a killer feature here is embedded this into the binary itself. Improves portability and resiliency across environments.

**Review by decentralgabe — COMMENTED** [review]
which version(s) of JSON Schema does this work with?

**Comment by KendallWeihe** [comment]
> which version(s) of JSON Schema does this work with?

We're using the `jsonschema` crate. 

From [the jsonschema crates.io page](https://crates.io/crates/jsonschema):

```
Supported drafts:

- Draft 7 (except optional idn-hostname.json test case)
- Draft 6
- Draft 4 (except optional bignum.json test case)

Partially supported drafts (some keywords are not implemented):

- Draft 2019-09 (requires the draft201909 feature enabled)
- Draft 2020-12 (requires the draft202012 feature enabled)
```

**Pull request merged**
