### PR TITLE
Add VS Code workspace

### PR DESCRIPTION
**Pull request by KendallWeihe**
This'll grow as we add more crates, so this get's us started

### CODE REVIEW

**Review by decentralgabe — APPROVED** [review]

**Review by decentralgabe — COMMENTED** [review]
not going to block but I don't love incorporating IDE specific files into shared workspaces.

**Comment by KendallWeihe** [comment]
> not going to block but I don't love incorporating IDE specific files into shared workspaces.

Ya know, I agree with this sentiment. We started doing this primarily for Hermit + Golang + FTL features but if we're really planning on these rust repos to be the core implementations for everything then I think that's right to not include IDE-specific matters. Can others weigh in on this matter?

**Review by nitro-neal — APPROVED** [review]
👍

**Comment by KendallWeihe** [comment]
Moving forward with this PR, stubbed in a issue on the backlog to discuss IDE-specific code assets https://github.com/TBD54566975/tbdex-rs/issues/46

**Pull request merged**
